name: Build on PR

on:
  pull_request: # run when pr is raised
    branches: 
      - master # run for master branch

jobs:
  build:
    runs-on: ubuntu-latest # os of github azure machine
    steps:
      - uses: actions/checkout@v3 # use pre existing repo cloning logic
      - name: Use Node.js
        uses: actions/setup-node@v3 # pre existing node setup logic
        with:
          node-version: '20'
      
      - name: Install Dependencies
        run: npm install
      - name: Generate Prisma Client
        run: npm run db:generate
      - name: Run Build
        run: npm run build
